// generated by stringer -type=countHookAction hook_count_action.go; DO NOT EDIT

package command

import "fmt"

const _countHookAction_name = "countHookActionAddcountHookActionChangecountHookActionRemove"

var _countHookAction_index = [...]uint8{18, 39, 60}

func (i countHookAction) String() string {
	if i >= countHookAction(len(_countHookAction_index)) {
		return fmt.Sprintf("countHookAction(%d)", i)
	}
	hi := _countHookAction_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _countHookAction_index[i-1]
	}
	return _countHookAction_name[lo:hi]
}
