// generated by stringer -type=GraphNodeConfigType graph_config_node_type.go; DO NOT EDIT

package terraform

import "fmt"

const _GraphNodeConfigType_name = "GraphNodeConfigTypeInvalidGraphNodeConfigTypeResourceGraphNodeConfigTypeProviderGraphNodeConfigTypeModuleGraphNodeConfigTypeOutputGraphNodeConfigTypeVariable"

var _GraphNodeConfigType_index = [...]uint8{26, 53, 80, 105, 130, 157}

func (i GraphNodeConfigType) String() string {
	if i < 0 || i >= GraphNodeConfigType(len(_GraphNodeConfigType_index)) {
		return fmt.Sprintf("GraphNodeConfigType(%d)", i)
	}
	hi := _GraphNodeConfigType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _GraphNodeConfigType_index[i-1]
	}
	return _GraphNodeConfigType_name[lo:hi]
}
