// generated by stringer -type=InstanceType instancetype.go; DO NOT EDIT

package terraform

import "fmt"

const _InstanceType_name = "TypeInvalidTypePrimaryTypeTaintedTypeDeposed"

var _InstanceType_index = [...]uint8{11, 22, 33, 44}

func (i InstanceType) String() string {
	if i < 0 || i >= InstanceType(len(_InstanceType_index)) {
		return fmt.Sprintf("InstanceType(%d)", i)
	}
	hi := _InstanceType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _InstanceType_index[i-1]
	}
	return _InstanceType_name[lo:hi]
}
