// generated by stringer -type=walkOperation graph_walk_operation.go; DO NOT EDIT

package terraform

import "fmt"

const _walkOperation_name = "walkInvalidwalkInputwalkApplywalkPlanwalkPlanDestroywalkRefreshwalkValidatewalkDestroy"

var _walkOperation_index = [...]uint8{11, 20, 29, 37, 52, 63, 75, 86}

func (i walkOperation) String() string {
	if i >= walkOperation(len(_walkOperation_index)) {
		return fmt.Sprintf("walkOperation(%d)", i)
	}
	hi := _walkOperation_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _walkOperation_index[i-1]
	}
	return _walkOperation_name[lo:hi]
}
